# Generated by Django 3.2.6 on 2021-08-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=150)),
                ('endereço', models.CharField(max_length=150)),
                ('ano', models.DateTimeField()),
            ],
        ),
    ]
